sudo: false
language: python
python:
- '2.7'
install:
- pip install lxml setuptools --upgrade
script:
- bash "./deploy.sh"
env:
  global:
  - ENCRYPTION_LABEL: "8a84087ed6cb"
  - COMMIT_AUTHOR_EMAIL: "plh+deploy@w3.org"
